// FIRST-RUN DEFAULTS ONLY. Everything here can be changed from the team area (Settings) without touching code,
// and the shop reads the saved values from the database. These values are used only until something is saved,
// or if the database cannot be reached. Do not edit this file to change prices or contact details: use Settings.
export const DEFAULT_SETTINGS = {
  store: {
    name: 'Tripple H Skin Luxe',
    tagline: 'Your beauty. Your ritual.',
    announce: 'Free delivery on orders over {{freeThreshold}} in Lagos',
    announceOn: true,
    whatsapp: '2348000000000',               // international format, digits only
    phone: '+234 800 000 0000',
    email: 'hello@lumebeauty.ng',            // placeholder: replace with the real address
    address: '15 Admiralty Way, Lekki Phase 1, Lagos, Nigeria',
    hours: 'Mon–Sat 9am–7pm · Sun 12pm–5pm',
    social: { instagram: 'https://www.instagram.com/tripplehskinluxe', tiktok: '', facebook: '', youtube: '', x: '' },
  },
  delivery: {
    lagosFee: 2000,
    otherFee: 4500,
    freeThreshold: 50000,
    lagosDays: '1–3 working days',
    otherDays: '3–7 working days',
    returnDays: 7,
    abandonAfterHours: 72,
    processingNote: 'Orders placed before 2pm on working days are processed the same day.',
  },
  ceo: {
    name: '',
    title: 'Founder & CEO',
    photo: '',
    quote: '',
    bio: [
      '{{name}} was built around a simple belief: caring for your skin and body should feel like a ritual, not a chore.',
      'Every product on the shelf and every treatment in the spa room is chosen with one question in mind: will it make someone feel genuinely looked after?',
      'From skincare to the spa, the goal is the same: honest products, calm spaces and service you can trust.',
    ],
    socials: { instagram: 'https://www.instagram.com/tripplehskinluxe', tiktok: '', facebook: '', youtube: '', x: '', whatsapp: '' },
  },
  spa: {
    headline: 'Spa & Wellness',
    intro: 'Slow down. Our treatments and spa essentials are designed to help you rest, reset and glow.',
    services: [
      { name: 'Signature Facial', duration: '60 min', from: null, description: 'A deep cleanse, gentle exfoliation, massage and hydrating mask tailored to your skin.' },
      { name: 'Aromatherapy Massage', duration: '60 min', from: null, description: 'A calming full-body massage with warm essential oils to ease tension.' },
      { name: 'Body Polish & Glow', duration: '75 min', from: null, description: 'A sugar-and-shea scrub followed by a nourishing wrap for soft, even-looking skin.' },
      { name: 'Hydrating Facial', duration: '45 min', from: null, description: 'Moisture-rich treatment for dry or dehydrated skin, finished with SPF.' },
      { name: 'Deep Tissue Massage', duration: '90 min', from: null, description: 'Firm, focused pressure for tight shoulders, back and legs.' },
      { name: 'Couples Spa Day', duration: '3 hrs', from: null, description: 'Side-by-side massages and facials in a private room, with tea and refreshments.' },
    ],
  },
  faq: {
    items: [
      { q: 'Are your products authentic?', a: 'Yes. We source directly from brands and trusted suppliers and never sell counterfeit products.' },
      { q: 'How long does delivery take?', a: 'Lagos orders arrive in {{lagosDays}}. Other states take {{otherDays}}.' },
      { q: 'Do you deliver outside Lagos?', a: 'Yes, we deliver to all 36 states and the FCT for a flat fee of {{otherFee}}.' },
      { q: 'How do I pay?', a: 'Checkout uses Paystack, so you can pay by card, bank transfer or USSD on a secure page.' },
      { q: 'Can I cancel an order?', a: 'You can cancel any time before it ships. Message us on WhatsApp with your order number.' },
      { q: 'Can I return a product?', a: 'Unopened products can be returned within {{returnDays}} days. Damaged or wrong items are replaced free of charge.' },
      { q: 'How do I track my order?', a: 'Open Track Order and enter your order number and phone number.' },
      { q: 'How do I book a spa treatment?', a: 'Go to the Spa & Wellness page and tap Book on WhatsApp. We will confirm a time with you.' },
      { q: 'How do I contact customer service?', a: 'Chat with us on WhatsApp, email {{email}}, or call {{phone}}.' },
    ],
  },
  about: {
    story: '{{name}} was created to make discovering quality beauty and wellness products simpler. We curate skincare, body care, hair care, fragrance and spa essentials so customers can shop with confidence.',
    sections: [
      { title: 'Why we started', text: 'Finding products you can trust should not mean scrolling through hundreds of options. We started with a small shelf of things we believe in and grew from there.' },
      { title: 'What we believe', text: 'Good routines are simple, consistent and personal. Beauty and wellness are about feeling comfortable in your skin, not chasing trends.' },
      { title: 'Authenticity', text: "We work with trusted suppliers and check every batch before it reaches you. If something isn't right, we'll make it right." },
      { title: 'Customer experience', text: 'From a clear product page to careful packaging, quick WhatsApp replies and a calm spa room, we try to make every step easy.' },
    ],
    trust: [
      { title: 'Authentic products', text: 'Sourced from trusted suppliers and brands.' },
      { title: 'Curated selection', text: 'A focused range, not a warehouse of everything.' },
      { title: 'Fast delivery', text: 'Quick in Lagos and dependable nationwide.' },
      { title: 'Customer support', text: 'Real people on WhatsApp, six days a week.' },
    ],
  },
};
